tests: refactor breakdown metrics tests to not override Agent internals (#2316)
This refactors breakdown.test.js to not need a resetAgent(...) that knows
so much about Agent internals. Now that we have a usable agent.destroy(),
use that and create a new Agent for each test case.

Unfortunately the change results in this test file running much slower.
See PR discussion for justification.

Also, protect against against a possible crash:
    TypeError: Cannot read property 'sendMetricSet' of null
in metrics/reporter.js if `agent.destroy()` has been called.