protect against agent.destroy() having happened in the meantime
Saw this in CI:
    # does not include transaction breakdown when disabled
    /home/runner/work/apm-agent-nodejs/apm-agent-nodejs/lib/metrics/reporter.js:56
	    this._agent._transport.sendMetricSet(metric)
				  ^
    TypeError: Cannot read property 'sendMetricSet' of null
	at afterAll (/home/runner/work/apm-agent-nodejs/apm-agent-nodejs/lib/metrics/reporter.js:56:31)
	at /home/runner/work/apm-agent-nodejs/apm-agent-nodejs/node_modules/after-all-results/index.js:20:25
	at _combinedTickCallback (internal/process/next_tick.js:131:7)